In [1]:
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
#import matplotlib.pyplot as plt

In [2]:
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

170500096/170498071 [==============================] - 49s 0us/step


In [7]:
train_images.shape, test_images.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [10]:
train_images[0].shape, test_images[0].shape

((32, 32, 3), (32, 32, 3))

In [14]:
train_labels.shape, test_labels.shape

((50000, 1), (10000, 1))

In [13]:
train_labels[0].shape, test_labels[0].shape

((1,), (1,))

In [19]:
train_labels, train_labels[0]

(array([[6],
        [9],
        [9],
        ...,
        [9],
        [1],
        [1]], dtype=uint8),
 array([6], dtype=uint8))

In [15]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

2022-01-09 17:35:05.878299: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-09 17:35:05.880120: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.


In [16]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 64)          36928     
Total params: 56,320
Trainable params: 56,320
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

In [18]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=10, 
                    validation_data=(test_images, test_labels))

Train on 50000 samples, validate on 10000 samples
Epoch 1/10
50000/50000 [==============================] - 36s 722us/sample - loss: 1.4967 - accuracy: 0.4520 - val_loss: 1.2056 - val_accuracy: 0.5748
Epoch 2/10
50000/50000 [==============================] - 32s 644us/sample - loss: 1.1396 - accuracy: 0.5980 - val_loss: 1.0817 - val_accuracy: 0.6224
Epoch 3/10
50000/50000 [==============================] - 33s 667us/sample - loss: 0.9776 - accuracy: 0.6575 - val_loss: 1.0028 - val_accuracy: 0.6412
Epoch 4/10
50000/50000 [==============================] - 39s 778us/sample - loss: 0.8796 - accuracy: 0.6931 - val_loss: 0.9234 - val_accuracy: 0.6765
Epoch 5/10
50000/50000 [==============================] - 42s 833us/sample - loss: 0.8127 - accuracy: 0.7143 - val_loss: 0.9101 - val_accuracy: 0.6898
Epoch 6/10
50000/50000 [==============================] - 42s 840us/sample - loss: 0.7515 - accuracy: 0.7372 - val_loss: 0.8958 - val_accuracy: 0.6971
Epoch 7/10
50000/50000 [====================

In [20]:
y_pred = model.predict(test_images)
y_pred.shape

(10000, 10)

In [11]:
test_labels

array([[3],
       [8],
       [8],
       ...,
       [5],
       [1],
       [7]], dtype=uint8)

In [21]:
y_pred

array([[-2.7624998 , -2.4015894 , -1.3120112 , ..., -3.1085973 ,
        -1.7259963 , -2.4368784 ],
       [ 5.9946904 ,  4.2997055 , -3.8514354 , ..., -7.070353  ,
         7.7540383 , -0.20719627],
       [ 2.5748358 ,  0.5301751 , -1.4414476 , ..., -1.6480097 ,
         2.8477664 ,  1.345597  ],
       ...,
       [-2.2132773 , -6.296965  ,  2.4394536 , ...,  0.5842038 ,
        -4.527878  , -7.6621785 ],
       [ 1.099849  ,  4.309068  , -0.5336648 , ..., -5.6340475 ,
        -5.029848  , -3.7130282 ],
       [-6.606876  , -6.6422505 , -0.63579774, ..., 13.0583105 ,
        -5.654244  , -2.7466512 ]], dtype=float32)