In [2]:
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
#import matplotlib.pyplot as plt

In [3]:
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

In [4]:
train_images.shape, test_images.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [5]:
train_images[0].shape, test_images[0].shape

((32, 32, 3), (32, 32, 3))

In [6]:
train_labels.shape, test_labels.shape

((50000, 1), (10000, 1))

In [7]:
train_labels[0].shape, test_labels[0].shape

((1,), (1,))

In [8]:
train_labels, train_labels[0]

(array([[6],
        [9],
        [9],
        ...,
        [9],
        [1],
        [1]], dtype=uint8),
 array([6], dtype=uint8))

In [9]:
train_images = tf.constant(train_images)
train_labels = tf.constant(train_labels)

In [10]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

In [11]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 64)          36928     
Total params: 56,320
Trainable params: 56,320
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

In [13]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=100, 
                    validation_data=(test_images, test_labels))

Epoch 1/100
1563/1563 [==============================] - 7s 3ms/step - loss: 1.5394 - accuracy: 0.4397 - val_loss: 1.2333 - val_accuracy: 0.5589
Epoch 2/100
1563/1563 [==============================] - 5s 3ms/step - loss: 1.1516 - accuracy: 0.5921 - val_loss: 1.1189 - val_accuracy: 0.6057
Epoch 3/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.9996 - accuracy: 0.6476 - val_loss: 1.0104 - val_accuracy: 0.6450
Epoch 4/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.9041 - accuracy: 0.6840 - val_loss: 0.9717 - val_accuracy: 0.6544
Epoch 5/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.8330 - accuracy: 0.7101 - val_loss: 0.8706 - val_accuracy: 0.7021
Epoch 6/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.7722 - accuracy: 0.7304 - val_loss: 0.8731 - val_accuracy: 0.6953
Epoch 7/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.7199 - accuracy: 0.7469 - val_loss: 0.9154 - val_ac

1563/1563 [==============================] - 5s 3ms/step - loss: 0.1139 - accuracy: 0.9606 - val_loss: 2.7513 - val_accuracy: 0.6838
Epoch 58/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.1015 - accuracy: 0.9650 - val_loss: 2.9052 - val_accuracy: 0.6707
Epoch 59/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.1083 - accuracy: 0.9636 - val_loss: 2.7604 - val_accuracy: 0.6861
Epoch 60/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.1123 - accuracy: 0.9625 - val_loss: 2.7975 - val_accuracy: 0.6855
Epoch 61/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.1089 - accuracy: 0.9625 - val_loss: 2.7460 - val_accuracy: 0.6762
Epoch 62/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.1051 - accuracy: 0.9645 - val_loss: 2.9356 - val_accuracy: 0.6835
Epoch 63/100
1563/1563 [==============================] - 5s 3ms/step - loss: 0.1043 - accuracy: 0.9641 - val_loss: 2.9573 - val_accuracy

In [31]:
y_pred = model.predict(test_images)
y_pred.shape

(10000, 10)

In [32]:
test_labels

array([[3],
       [8],
       [8],
       ...,
       [5],
       [1],
       [7]], dtype=uint8)

In [19]:
y_pred[1]

array([ 3.7401547,  3.0914576, -4.5112987, -4.901181 , -4.083057 ,
       -9.621651 , -7.659369 , -6.2044415,  7.4889765,  2.9381797],
      dtype=float32)